replicas: 1

watchAnyNamespace: false
watchNamespaces:
  - kafka-connect

nodeSelector:
  role: system

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    memory: 512Mi

leaderElection:
  enable: true
