settings:
  clusterName: kube-system-eks
  interruptionQueue: kube-system-karpenter

serviceAccount:
  name: karpenter

nodeSelector:
  role: system

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists

controller:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      memory: 1Gi
