apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: airflow
spec:
  role: kube-system-karpenter-node

  amiSelectorTerms:
    - alias: al2023@latest

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: kube-system-eks

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: kube-system-eks
    - name: kube-system-airflow-nodes

  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true

  tags:
    Project: kube-system
    ManagedBy: karpenter
    Workload: airflow
