hook:
  upgradeCrd: true

  nodeSelector:
    role: system

  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists

controller:
  replicas: 1

  nodeSelector:
    role: system

  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 512Mi

webhook:
  enable: true
  replicas: 1

  nodeSelector:
    role: system

  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 256Mi

spark:
  jobNamespaces:
    - spark-jobs

  serviceAccount:
    create: true
    name: spark

  rbac:
    create: true
